export const coursesSection= {
    content : `<h1 className='saya'>About Me</h1>
      <p className='text-base/loose text-center opacity-50' >Berikut ini beberapa perkenalan dari saya</p>
        <p className="paragraph">
            Halo, saya Dimas Febri Maulana Ishaq.
         Saya adalah seorang mahasiswa Teknik Informatika di STMIK Widya Utama Purwokerto, 
         yang memiliki ketertarikan besar pada dunia teknologi, pemrograman, dan desain digital. 
         Sebelum memasuki dunia perkuliahan, saya juga pernah menempuh pendidikan di Pondok Pesantren 
         Attholibiyah Bumijawa, Tegal — tempat di mana saya banyak belajar tentang kedisiplinan, 
         nilai-nilai kehidupan, serta semangat untuk terus berkembang.
         Ketertarikan saya terhadap dunia teknologi bermula sejak pertama kali saya berinteraksi 
         dengan komputer dan mencoba menulis baris kode sederhana. Dari situ, saya mulai menyadari 
         bahwa dengan logika dan kreativitas, saya bisa menciptakan sesuatu yang nyata — entah itu 
         sebuah aplikasi, website, atau sistem yang membantu menyelesaikan masalah di dunia nyata.
         Seiring waktu, saya mulai mempelajari berbagai bahasa dan teknologi seperti HTML, 
         CSS, JavaScript, hingga framework modern seperti ReactJS dan Node.js. 
         Saya menikmati proses membangun sebuah website dari nol — mulai dari merancang struktur logikanya, 
         hingga mendesain tampilannya agar menarik dan mudah digunakan.
         Namun bagi saya, pengalaman pengguna (user experience) tak kalah penting dari 
         fungsionalitas. Karena itu, saya juga mendalami dunia desain antarmuka melalui UI/UX Design. 
         Saya terbiasa menggunakan tools seperti Figma, Canva, dan terkadang Photoshop untuk menciptakan 
         desain yang bukan hanya estetis, tapi juga intuitif dan efisien.
         Saya percaya bahwa perpaduan antara logika dalam pemrograman dan estetika dalam 
         desain adalah kunci untuk menciptakan produk digital yang hebat. Ketika menulis kode, 
         saya merasa seperti membangun fondasi yang kokoh. Dan ketika saya mendesain tampilan, 
         saya seperti memberikan "jiwa" pada produk tersebut — menjadikannya hidup, menarik, 
         dan menyenangkan untuk digunakan.
         Ke depannya, saya ingin menjadi seorang developer yang holistik — 
         bukan hanya mahir dalam teknis, tetapi juga mampu menghadirkan solusi digital yang fungsional, 
         profesional, dan user-centric. Saya ingin menciptakan karya-karya yang berdampak 
         dan bermanfaat bagi banyak orang.
         Karena bagi saya, dunia teknologi bukan sekadar karier — t
         api sebuah perjalanan pembelajaran tanpa akhir. Dan saya siap untuk 
         terus melangkah, menjelajahi hal-hal baru, dan tumbuh bersama perkembangan zaman. </p>`

}